"""empty message

Revision ID: 3084a9f61b5c
Revises: c5729feac5c6
Create Date: 2024-08-25 15:48:39.889402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3084a9f61b5c'
down_revision = 'c5729feac5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Stored', 'Supplied', 'Expired', name='blood_status_enum'), nullable=True))

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Requested', 'Completed', 'Cancelled', name='status_enum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Requested', 'Completed', 'Cancelled', name='status_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('blood_donation', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
